### ISSUE TITLE
productivity modules

### ISSUE THREAD

**Issue by 23johnw** [walter-exit/factorio_sr#2]
i can't seem to add productivity modules to refineries, i had a look at the code and it should allow them i think, i may be wrong. Is this intentional i can add productivity modules to vanilla refineries, thanks

**Comment by walter-exit** [comment]
Hi John,

No, this is not intentional. Any module should be able to fit into these refineries. I haven't played recently, and I do know they change the game a lot, so I probably need to update this mod to get it working again.

It would mean I need to take a look at the official refinery code of the game, see what changed, and then apply those changes to the mod.

Due to the game being still heavily under development, this happens once every few weeks or months. Sorry.

I'll release a new update soon. Hopefully tomorrow if my private life allows me.

Much thanks for notifying me, it helps a lot to keep this mod up and running.

**Comment by 23johnw** [comment]
Great for getting back so quick, I understand life gets in the way of factorio, it comes up with something like "only use productity on intermediate products" I had a look at the code for your refinery and the base game and it all looked the same. Cheers

**Comment by walter-exit** [comment]
I found the problem. The productivity module explicitly requires to have all the allowed intermediate products (recipies) listed in order for it to be allowed in any building.

This behaviour was probably like this from the start. But I'll release 1.3.2 today with a fix. This version will add my specialized refinery recipes to the allowed intermediate products for productivity modules.

I tried it in-game and it worked. I'd love to hear from you if it is solved in 1.3.2

**Comment by 23johnw** [comment]
Hi, it's allowing me to insert productivity module 1 not 2 or 3, still comes up with "productivity only allowed for  intermediate Product",

thanks for the quick response/ help
much appreciated

john

**Comment by 23johnw** [comment]
i am only using your mod and creative mod, just to allow all research on a new game to try it,

**Comment by 23johnw** [comment]
require("config")
require("core")
require("prototypes.category")
require("prototypes.entities")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.technology")
data.raw["assembling-machine"]["oil-refinery"].fast_replaceable_group = "assembling-machine"
-- Allow productivity modules in the specialized refineries by adding the recipies as intermediate products
table.insert(data.raw.module["productivity-module"].limitation, "specialized-refining-petroleum")
table.insert(data.raw.module["productivity-module"].limitation, "specialized-refining-light-oil")
table.insert(data.raw.module["productivity-module"].limitation, "specialized-refining-heavy-oil")
table.insert(data.raw.module["productivity-module-2"].limitation, "specialized-refining-petroleum")
table.insert(data.raw.module["productivity-module-2"].limitation, "specialized-refining-light-oil")
table.insert(data.raw.module["productivity-module-2"].limitation, "specialized-refining-heavy-oil")
table.insert(data.raw.module["productivity-module-3"].limitation, "specialized-refining-petroleum")
table.insert(data.raw.module["productivity-module-3"].limitation, "specialized-refining-light-oil")
table.insert(data.raw.module["productivity-module-3"].limitation, "specialized-refining-heavy-oil")

**Comment by 23johnw** [comment]
That fixed it, looks like you have to name all the productivity modules separately.
cheers

**Comment by walter-exit** [comment]
Ah, this needs to be done per module?

In that case the commit from atehxx is indeed more near, now I get it.

https://github.com/walter-exit/factorio_sr/commit/c3ba21f89787ee106c68b2512389a9226675e779

I'll update to 1.3.3 asap for everybody else

Thanks for your help John

**Comment by walter-exit** [comment]
I meant neat, not near

**Comment by 23johnw** [comment]
No problems, you did most of the work i just played with it.

thanks for making a great mod
