### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by 23johnw** [walter-exit/factorio_sr#3]
Ran the mod update and it crashes the game.
Attempted fresh install of mod and also crashed with same error message.
failed to load mods: specialized_refineris/data.lua:13:bad argument #1 to 'insert' (table expected, got nil)

this is what some one put on mods.factorio , i ran mod and got same error

**Comment by walter-exit** [comment]
Which version of the game are you running?

Most players seem to be in the experimental 0.15.x series. It should work there.

Let me know

**Comment by walter-exit** [comment]
PS, you can download 1.3.1 from the factorio mod website to be able to play. 1.3.1 just doesnt support productivity modules in the specialized refinery
